name: Deploy to internal services
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger deployment at onboarding.extendify.com
              uses: fjogeleit/http-request-action@master
              with:
                  url: ${{ secrets.DEPLOY_WEBHOOK_ONBOARDING }}
                  method: 'POST'
            - name: Trigger deployment at launch.extendify.com
              uses: fjogeleit/http-request-action@master
              with:
                  url: ${{ secrets.DEPLOY_WEBHOOK_LAUNCH }}
                  method: 'POST'
